-- ============================================================
-- PORTAL DE LUZ — UPIS Las Palmeras del Sol
-- Schema SQL para Supabase (PostgreSQL)
-- Pegar en: Supabase Dashboard > SQL Editor > New Query
-- ============================================================

-- 1. ENUMS
CREATE TYPE estado_lote AS ENUM ('HABITADO', 'SOLO_MANTENIMIENTO', 'BALDIO');
CREATE TYPE estado_pago AS ENUM ('PENDIENTE', 'PAGADO', 'VENCIDO');
CREATE TYPE estado_periodo AS ENUM ('ABIERTO', 'CERRADO');

-- 2. TABLA LOTES
-- Directorio de vecinos y propiedades. No se repite mes a mes.
CREATE TABLE lotes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manzana     CHAR(1)      NOT NULL,           -- 'A', 'B', 'C'...
    lote_numero INT          NOT NULL,            -- 1, 2, 17...
    nombres     VARCHAR(100),
    apellidos   VARCHAR(100),
    dni         VARCHAR(20),                      -- Para consulta pública por DNI
    tipo_servicio estado_lote DEFAULT 'HABITADO',
    created_at  TIMESTAMPTZ  DEFAULT NOW(),

    CONSTRAINT uq_lote_manzana UNIQUE (manzana, lote_numero)
);

-- 3. TABLA TARIFAS MENSUALES
-- Configuración de precios por mes. Se define UNA VEZ por período.
CREATE TABLE tarifas_mensuales (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo          DATE         NOT NULL,        -- '2026-01-01' para Enero 2026
    precio_kwh       DECIMAL(10, 4) NOT NULL DEFAULT 0.86,
    costo_alumbrado  DECIMAL(10, 2) NOT NULL DEFAULT 10.00,
    estado           estado_periodo DEFAULT 'ABIERTO',
    created_at       TIMESTAMPTZ  DEFAULT NOW(),

    CONSTRAINT uq_periodo UNIQUE (periodo)
);

-- 4. TABLA RECIBOS
-- Registro histórico de consumo por lote por mes.
-- Los precios se COPIAN al momento de crear el recibo (snapshot inmutable).
CREATE TABLE recibos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id          BIGINT REFERENCES lotes(id) ON DELETE RESTRICT,
    tarifa_id        BIGINT REFERENCES tarifas_mensuales(id) ON DELETE RESTRICT,

    -- Inputs
    consumo_kwh      DECIMAL(10, 2) NOT NULL DEFAULT 0,
    precio_x_kwh     DECIMAL(10, 4) NOT NULL,     -- Snapshot del precio del mes
    alumbrado_publico DECIMAL(10, 2) NOT NULL,     -- Snapshot del alumbrado del mes

    -- Cálculos automáticos (columnas generadas)
    -- Columna J del Excel: consumo * precio + alumbrado
    total_consumo    DECIMAL(10, 3)
        GENERATED ALWAYS AS (
            (consumo_kwh * precio_x_kwh) + alumbrado_publico
        ) STORED,

    -- Columna K del Excel: redondeado al entero más cercano
    total_recibo     INTEGER
        GENERATED ALWAYS AS (
            ROUND((consumo_kwh * precio_x_kwh) + alumbrado_publico)
        ) STORED,

    estado           estado_pago DEFAULT 'PENDIENTE',
    fecha_pago       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ DEFAULT NOW(),

    -- Un lote solo puede tener un recibo por período
    CONSTRAINT uq_lote_tarifa UNIQUE (lote_id, tarifa_id)
);

-- 5. ÍNDICES para búsquedas frecuentes
CREATE INDEX idx_recibos_lote_id ON recibos(lote_id);
CREATE INDEX idx_recibos_tarifa_id ON recibos(tarifa_id);
CREATE INDEX idx_recibos_estado ON recibos(estado);
CREATE INDEX idx_lotes_dni ON lotes(dni);
CREATE INDEX idx_tarifas_estado ON tarifas_mensuales(estado);

-- 6. ROW LEVEL SECURITY (RLS)
ALTER TABLE lotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE tarifas_mensuales ENABLE ROW LEVEL SECURITY;
ALTER TABLE recibos ENABLE ROW LEVEL SECURITY;

-- Lectura pública (vecinos pueden ver sin login)
CREATE POLICY "Lectura pública de lotes"
    ON lotes FOR SELECT USING (true);

CREATE POLICY "Lectura pública de tarifas"
    ON tarifas_mensuales FOR SELECT USING (true);

CREATE POLICY "Lectura pública de recibos"
    ON recibos FOR SELECT USING (true);

-- Solo usuarios autenticados pueden escribir
CREATE POLICY "Admin puede insertar lotes"
    ON lotes FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Admin puede actualizar lotes"
    ON lotes FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Admin puede insertar tarifas"
    ON tarifas_mensuales FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Admin puede actualizar tarifas"
    ON tarifas_mensuales FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Admin puede insertar recibos"
    ON recibos FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Admin puede actualizar recibos"
    ON recibos FOR UPDATE TO authenticated USING (true);

-- 7. DATOS DE EJEMPLO (opcional, comentar si no se necesita)
-- INSERT INTO lotes (manzana, lote_numero, nombres, apellidos, tipo_servicio) VALUES
--     ('A', 1,  'EMER DAVID',  'DE LA CRUZ CORDOVA',  'HABITADO'),
--     ('A', 2,  'CARLOS',      'BENITES GUERRERO',     'HABITADO'),
--     ('A', 10, 'IRVING',      'CHIROQUE SALAZAR',     'SOLO_MANTENIMIENTO'),
--     ('A', 11, 'GERSON',      'GOMEZ CAMACHO',        'SOLO_MANTENIMIENTO'),
--     ('A', 17, 'CARLOS',      'GOMEZ MERINO',         'HABITADO'),
--     ('A', 18, 'DAVID',       'GUARDIA MEZA',         'HABITADO'),
--     ('A', 21, 'JORGE',       'ROSILLO PALACIOS',     'SOLO_MANTENIMIENTO'),
--     ('A', 24, 'HOWAR',       'CONCHA SARANGO',       'SOLO_MANTENIMIENTO'),
--     ('A', 26, 'CARLOS',      'CORREA ECA',           'HABITADO'),
--     ('A', 29, 'KARINA',      'ORTIZ CARMEN',         'HABITADO');
