-- ============================================================
-- PORTAL DE LUZ — UPIS Las Palmeras del Sol
-- Schema SQL para Supabase (PostgreSQL)
-- Pegar en: Supabase Dashboard > SQL Editor > New Query
-- ============================================================

-- 1. ENUMS
CREATE TYPE estado_lote AS ENUM ('HABITADO', 'SOLO_MANTENIMIENTO', 'BALDIO');
CREATE TYPE estado_pago AS ENUM ('PENDIENTE', 'PAGADO', 'VENCIDO');
CREATE TYPE estado_periodo AS ENUM ('ABIERTO', 'CERRADO');

-- ============================================================
-- 2. TABLA LOTES
-- Directorio de vecinos y propiedades. No se repite mes a mes.
-- ============================================================
CREATE TABLE lotes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manzana       CHAR(1)       NOT NULL,           -- 'A', 'B', 'C'...
    lote_numero   INT           NOT NULL,            -- 1, 2, 17...
    nombres       VARCHAR(100),
    apellidos     VARCHAR(100),
    dni           VARCHAR(8)    UNIQUE,              -- DNI peruano (8 dígitos). Permite consulta pública sin login.
    tipo_servicio estado_lote   DEFAULT 'HABITADO',
    created_at    TIMESTAMPTZ   DEFAULT NOW(),

    -- No puede haber dos Lote 1 en la Manzana A
    CONSTRAINT uq_lote_manzana UNIQUE (manzana, lote_numero)
);

COMMENT ON TABLE lotes IS 'Directorio de vecinos y propiedades de UPIS Las Palmeras del Sol';
COMMENT ON COLUMN lotes.dni IS 'DNI peruano de 8 dígitos. Usado para consulta pública sin login.';

-- ============================================================
-- 3. TABLA TARIFAS MENSUALES
-- Configuración de precios por mes. Se define UNA VEZ por período.
-- ============================================================
CREATE TABLE tarifas_mensuales (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo          DATE          NOT NULL,        -- '2026-01-01' para Enero 2026
    precio_kwh       DECIMAL(10,4) NOT NULL DEFAULT 0.86,
    costo_alumbrado  DECIMAL(10,2) NOT NULL DEFAULT 10.00,
    estado           estado_periodo DEFAULT 'ABIERTO',
    created_at       TIMESTAMPTZ   DEFAULT NOW(),

    CONSTRAINT uq_periodo UNIQUE (periodo)
);

COMMENT ON TABLE tarifas_mensuales IS 'Histórico de precios unitarios por mes. Un registro por período.';

-- ============================================================
-- 4. TABLA RECIBOS
-- Registro histórico de consumo por lote por mes.
-- Los precios se COPIAN al momento de crear el recibo (snapshot inmutable).
-- ============================================================
CREATE TABLE recibos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id           BIGINT REFERENCES lotes(id) ON DELETE RESTRICT,
    tarifa_id         BIGINT REFERENCES tarifas_mensuales(id) ON DELETE RESTRICT,

    -- Inputs (lo que ingresa el admin)
    consumo_kwh       DECIMAL(10,2) NOT NULL DEFAULT 0,
    precio_x_kwh      DECIMAL(10,4) NOT NULL,       -- Snapshot del precio del mes
    alumbrado_publico DECIMAL(10,2) NOT NULL,        -- Snapshot del alumbrado del mes

    -- Cálculos automáticos (columnas generadas por PostgreSQL)
    -- Equivalente a la Columna J del Excel: consumo * precio + alumbrado
    total_consumo     DECIMAL(10,3)
        GENERATED ALWAYS AS (
            (consumo_kwh * precio_x_kwh) + alumbrado_publico
        ) STORED,

    -- Equivalente a la Columna K del Excel: redondeado HACIA ARRIBA (CEIL)
    -- Ej: 14.3 → 15, no 14
    total_recibo      INTEGER
        GENERATED ALWAYS AS (
            CEIL((consumo_kwh * precio_x_kwh) + alumbrado_publico)
        ) STORED,

    estado            estado_pago   DEFAULT 'PENDIENTE',
    fecha_pago        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ   DEFAULT NOW(),

    -- Un lote solo puede tener un recibo por período
    CONSTRAINT uq_lote_tarifa UNIQUE (lote_id, tarifa_id)
);

COMMENT ON TABLE recibos IS 'Historial de consumo y cobros por lote por mes.';
COMMENT ON COLUMN recibos.precio_x_kwh IS 'Snapshot del precio al momento de crear el recibo. No cambia si sube la tarifa.';
COMMENT ON COLUMN recibos.total_recibo IS 'Total redondeado HACIA ARRIBA (CEIL). Calculado automáticamente por PostgreSQL.';

-- ============================================================
-- 5. ÍNDICES para búsquedas frecuentes
-- ============================================================
CREATE INDEX idx_recibos_lote_id   ON recibos(lote_id);
CREATE INDEX idx_recibos_tarifa_id ON recibos(tarifa_id);
CREATE INDEX idx_recibos_estado    ON recibos(estado);
CREATE INDEX idx_lotes_dni         ON lotes(dni);          -- Búsqueda pública por DNI
CREATE INDEX idx_tarifas_estado    ON tarifas_mensuales(estado);

-- ============================================================
-- 6. ROW LEVEL SECURITY (RLS)
-- Crítico: nadie puede borrar/modificar data sin autenticación.
-- ============================================================
ALTER TABLE lotes             ENABLE ROW LEVEL SECURITY;
ALTER TABLE tarifas_mensuales ENABLE ROW LEVEL SECURITY;
ALTER TABLE recibos           ENABLE ROW LEVEL SECURITY;

-- Lectura pública (vecinos pueden ver sin login)
CREATE POLICY "Lectura pública de lotes"
    ON lotes FOR SELECT USING (true);

CREATE POLICY "Lectura pública de tarifas"
    ON tarifas_mensuales FOR SELECT USING (true);

CREATE POLICY "Lectura pública de recibos"
    ON recibos FOR SELECT USING (true);

-- Solo usuarios autenticados (admin) pueden escribir
CREATE POLICY "Admin puede insertar lotes"
    ON lotes FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Admin puede actualizar lotes"
    ON lotes FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Admin puede insertar tarifas"
    ON tarifas_mensuales FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Admin puede actualizar tarifas"
    ON tarifas_mensuales FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Admin puede insertar recibos"
    ON recibos FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Admin puede actualizar recibos"
    ON recibos FOR UPDATE TO authenticated USING (true);

-- ============================================================
-- 7. DATOS DE EJEMPLO (descomentar para poblar la BD inicial)
-- ============================================================
-- INSERT INTO lotes (manzana, lote_numero, nombres, apellidos, dni, tipo_servicio) VALUES
--     ('A',  1,  'EMER DAVID',   'DE LA CRUZ CORDOVA',  '12345678', 'HABITADO'),
--     ('A',  2,  'CARLOS',       'BENITES GUERRERO',    '23456789', 'HABITADO'),
--     ('A', 10,  'IRVING',       'CHIROQUE SALAZAR',    '34567890', 'SOLO_MANTENIMIENTO'),
--     ('A', 11,  'GERSON',       'GOMEZ CAMACHO',       '45678901', 'SOLO_MANTENIMIENTO'),
--     ('A', 17,  'CARLOS',       'GOMEZ MERINO',        '56789012', 'HABITADO'),
--     ('A', 18,  'DAVID',        'GUARDIA MEZA',        '67890123', 'HABITADO'),
--     ('A', 21,  'JORGE',        'ROSILLO PALACIOS',    '78901234', 'SOLO_MANTENIMIENTO'),
--     ('A', 24,  'HOWAR',        'CONCHA SARANGO',      '89012345', 'SOLO_MANTENIMIENTO'),
--     ('A', 26,  'CARLOS',       'CORREA ECA',          '90123456', 'HABITADO'),
--     ('A', 29,  'KARINA',       'ORTIZ CARMEN',        '01234567', 'HABITADO');

-- INSERT INTO tarifas_mensuales (periodo, precio_kwh, costo_alumbrado, estado) VALUES
--     ('2026-02-01', 0.86, 10.00, 'ABIERTO');